name: Build Docker Image And Push Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build And Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/activities-backend .

      - name: Push Image to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/activities-backend

      - name: Connecting and Deploying to the SSH Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /
            cd /docker/activities
            docker rm -f activities-api
            docker rmi a4sufpb/activities-backend
            docker compose up -d